# Generated by Django 5.1.1 on 2024-09-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order', 'id'), 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
    ]
