# Generated by Django 5.1.1 on 2024-09-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_remove_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_urls',
            field=models.JSONField(default=list),
        ),
    ]
