# Generated by Django 5.1.1 on 2024-09-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_image_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentimage',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_image_url',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
