# Generated by Django 5.1.1 on 2024-10-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
