# Generated by Django 5.1.1 on 2025-01-09 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_urls',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='product.product'),
        ),
    ]
