# Generated by Django 5.1.1 on 2025-02-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_category_name_en_remove_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.IntegerField(choices=[(0, 'Kilogram'), (1, 'Gram'), (2, 'Litre'), (3, 'Piece')], default=1),
        ),
    ]
