# Generated by Django 5.1.1 on 2025-02-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='worth',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
    ]
