# Generated by Django 5.1.1 on 2024-11-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_promo_min_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_ordered',
        ),
    ]
