# Generated by Django 5.1.1 on 2025-01-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userlocation_user'),
        ('order', '0005_remove_cartitem_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_location', to='account.userlocation'),
        ),
    ]
