# Generated by Django 5.1.1 on 2025-02-10 12:00

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
