# Generated by Django 5.1.1 on 2025-07-13 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('order', '0009_remove_order_is_delivered_order_assigned_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
    ]
