# Generated by Django 5.1.1 on 2025-07-18 13:39

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_courier_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
