# Generated by Django 5.1.1 on 2024-09-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.CharField(default=1, max_length=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.CharField(default=1, max_length=123),
            preserve_default=False,
        ),
    ]
