# Generated by Django 5.1.1 on 2025-01-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_latitude_remove_user_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='apartment',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='floor',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Location_image/'),
        ),
    ]
