# Generated by Django 5.1.1 on 2025-01-04 17:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userlocation_apartment_userlocation_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlocation',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
