# Generated by Django 5.1.1 on 2025-01-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userlocation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='new_block_image/')),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
