# Generated by Django 5.1.1 on 2025-01-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_newblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='location',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
    ]
