# Generated by Django 5.1.1 on 2025-01-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userlocation_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlocation',
            name='image',
        ),
    ]
