# Generated by Django 5.1.1 on 2025-01-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_advice_alter_userlocation_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=123, null=True)),
                ('url', models.CharField(blank=True, max_length=123, null=True)),
            ],
        ),
    ]
