# Generated by Django 5.1.1 on 2025-02-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_carta_name', models.CharField(max_length=123)),
                ('bank_name', models.CharField(max_length=123)),
                ('carta_number', models.CharField(max_length=123)),
                ('bank_number', models.IntegerField()),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
